version: "3.8"

services:
  database:
    container_name: rnlimawebsite
    image: postgres
    volumes:
      - ./.pgdata:/Program Files/PostgreSQL/12/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=rnweblima
      - POSTGRES_USER=rnlima
      - POSTGRES_DB=rnlimawebsite
    ports:
      - 5434:5432
